channels:
  - pytorch
  - defaults
  # using conda-forge for python v3.9+
  - conda-forge
dependencies:
  - pytest
  - pytest-cov
  - codecov
  - pip
  - libpng
  - jpeg
  - ca-certificates
  - pip:
    - future
    - pillow>=4.1.1
    - scipy
    - av
