channels:
  - pytorch
  - defaults
  # using conda-forge for python v3.9
  - conda-forge
dependencies:
  - pytest
  - pytest-cov
  - codecov
  - pip
  - libpng
  # NOTE: Pinned to fix issues with size_t on Windows
  - jpeg <=9b
  - ca-certificates
  - pip:
    - future
    - pillow >=5.3.0
    - scipy
    - av
