channel_sources:
  - pytorch-nightly,pytorch,defaults
blas_impl:
  - mkl                        # [x86_64]
c_compiler:
  - vs2017                     # [win]
cxx_compiler:
  - vs2017                     # [win]
python:
  - 3.5
  - 3.6
# This differs from target_platform in that it determines what subdir the compiler
#    will target, not what subdir the compiler package will be itself.
#    For example, we need a win-64 vs2008_win-32 package, so that we compile win-32
#    code on win-64 miniconda.
cross_compiler_target_platform:
  - win-64                     # [win]
target_platform:
  - win-64                     # [win]
vc:
  - 14
zip_keys:
  -                             # [win]
    - vc                        # [win]
    - c_compiler                # [win]
    - cxx_compiler              # [win]
