channels:
  - pytorch
  - defaults
dependencies:
  - pytest
  - pytest-cov
  - pytest-mock
  - pip
  - libpng
  # NOTE: Pinned to fix issues with size_t on Windows
  - jpeg <=9b
  - ca-certificates
  - pip:
    - future
    - pillow >=5.3.0
    - scipy
    - av
    - dataclasses
