channels:
  - pytorch
  - defaults
dependencies:
  - pytest
  - pytest-cov
  - pytest-mock
  - pip
  - libpng
  - jpeg
  - ca-certificates
  - hdf5
  - setuptools
  - pip:
    - future
    - scipy
    - av != 9.1.1
    - dataclasses
    - h5py
