name: tests

on:
  pull_request:

jobs:
  prototype:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
      fail-fast: false

    runs-on: ${{ matrix.os }}

    steps:
#      - name: Set up python
#        uses: actions/setup-python@v3
#        with:
#          python-version: 3.7
#
#      - name: Upgrade system packages
#        run: python -m pip install --upgrade pip setuptools wheel
#
#      - name: Checkout repository
#        uses: actions/checkout@v3
#
#      - name: Install PyTorch nightly builds
#        run: pip install --progress-bar=off --pre torch torchdata --extra-index-url https://download.pytorch.org/whl/nightly/cpu/
#
#      - name: Install torchvision
#        run: pip install --progress-bar=off --no-build-isolation --editable .
#
#      - name: Install other prototype dependencies
#        run: pip install --progress-bar=off scipy pycocotools h5py iopath
#
#      - name: Install test requirements
#        run: pip install --progress-bar=off pytest pytest-mock

      - name: Mark setup as complete
        id: setup
        run: exit 0

      - name: Check conclusion
        run: echo ${{ steps.setup.conclusion }}

      - name: Failure
        run: exit 1

      - name: Use in condition
        if: ${{ success() || ( failure() && steps.setup.conclusion == 'success' ) }}
        run: echo WOOHOO

#      - name: Run prototype datasets tests
#        shell: bash
#        run: |
#          pytest \
#            --durations=20 \
#            --cov=torchvision/prototype/datasets \
#            --cov-report=term-missing \
#            test/test_prototype_datasets*.py
#
#      - name: Run prototype transforms tests
#        shell: bash
#        run: |
#          pytest \
#            --durations=20 \
#            --cov=torchvision/prototype/transforms \
#            --cov-report=term-missing \
#            test/test_prototype_transforms*.py
#
#      - name: Run prototype models tests
#        if: ${{ steps.setup.conclusion == 'success' }}
#        shell: bash
#        run: |
#          pytest \
#            --durations=20 \
#            --cov=torchvision/prototype/models \
#            --cov-report=term-missing \
#            test/test_prototype_models*.py
